- name: Run tests and generate TRX log  # Запуск тестов
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"

    - name: Test Report		# Сохранение отчета
      uses: dorny/test-reporter@v2
      if: success() || failure() # запускает этот шаг в любом случае
      with:
        name: Test results          
        path: "**/*.trx"    # Путь сохранения результатов теста
        reporter: dotnet-trx   # Формат результата
